Repository Kusitms-28th-Hicardi-C/FrontEnd, pull requests merged in 2023-09, with the labels that each got.

#4 [Feat] 메인 페이지 수정
  src/pages/main/main.tsx
Labels: feat

#9 [Design] 네비게이션 바 완성
  public/index.html
  src/Router.tsx
  src/assets/icons/search.svg
  src/assets/icons/user.svg
  src/assets/logo/hicardi-logo.svg
  src/components/navbar/Navbar.tsx
  src/pages/main/MainPage.tsx
  src/pages/main/main.tsx
  src/styles/GlobalStyle.ts
Labels: design

#11 [Design] 고객 지원 페이지
  src/Router.tsx
  src/assets/.gitkeep
  src/assets/client/howToUse.svg
  src/assets/client/product.svg
  src/assets/client/questionMark.svg
  src/components/.gitkeep
  src/components/client/Support.tsx
  src/components/client/UsageInquiry.tsx
  src/pages/client/ClientPage.tsx
  src/styles/theme.ts
Labels: design

#12 [Design] 메인 페이지 일부 완성
  src/assets/banners/banner1.png
  src/assets/intro/intro1.png
  src/assets/signs/quotes.svg
  src/assets/signs/right-arrow.svg
  src/assets/supports/supports.png
  src/components/main/Banner.tsx
  src/components/main/Intro.tsx
  src/components/main/Review.tsx
  src/components/main/SectionDescription.tsx
  src/components/main/SectionTitle.tsx
  src/components/main/Support.tsx
  src/pages/main/MainPage.tsx
  src/styles/theme.ts
Labels: design

#13 [Design] 고객 문의 페이지 완료
  src/Router.tsx
  src/assets/client/arrow.svg
  src/assets/client/download.svg
  src/assets/client/hand.svg
  src/assets/client/video.svg
  src/assets/icons/rightArrow.svg
  src/components/client/FAQ.tsx
  src/components/client/HowToUse.tsx
  src/components/client/Inquiry.tsx
  src/components/client/Product.tsx
  src/components/client/Support.tsx
  src/components/client/UsageInquiry.tsx
  src/components/common/Button.tsx
  src/components/main/Intro.tsx
  src/pages/client/ClientPage.tsx
  src/styles/theme.ts
Labels: design

#23 [Design] 로그인, 회원가입 페이지
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/auth/arrow.svg
  src/assets/auth/checked.svg
  src/components/auth/Agreement.tsx
  src/components/auth/ButtonBox.tsx
  src/components/auth/Complete.tsx
  src/components/auth/Index.tsx
  src/components/auth/Information.tsx
  src/components/auth/Login.tsx
  src/components/client/FAQ.tsx
  src/components/common/Button.tsx
  src/components/common/CheckBox.tsx
  src/components/common/Input.tsx
  src/components/common/Textarea.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
  src/styles/theme.ts
Labels: design

#31 [Fix] 다른 창으로 이동 시 드롭다운 없애기
  src/components/navbar/Navbar.tsx
Labels: fix

#34 [Design] favicon 이미지 외곽 테두리 삭제
  public/favicon.png
Labels: design

#37 [Feat] 제품 상세 페이지 파일 추가
  src/Router.tsx
  src/pages/ProductDetailPage.tsx
Labels: feat

#38 [Design] 고객지원, 로그인, 회원가입
  src/Router.tsx
  src/components/auth/Login.tsx
  src/components/client/FAQ.tsx
  src/components/client/HowToUse.tsx
  src/components/client/Product.tsx
  src/components/client/Support.tsx
  src/components/client/UsageInquiry.tsx
  src/components/common/Button.tsx
  src/components/common/ScrollTop.tsx
  src/components/footer/Description.tsx
  src/components/footer/Footer.tsx
  src/components/footer/Inquiry.tsx
  src/pages/ClientPage.tsx
  src/pages/auth/SignupPage.tsx
  src/styles/theme.ts
Labels: design

#42 [Design] 제품 상세 페이지 스타일링하기
  src/Router.tsx
  src/assets/products/hicardi+.png
  src/components/product-detail/Heading.tsx
  src/components/product-detail/ProductDetail.tsx
  src/components/product-detail/ProductInfoImage.tsx
  src/components/product-list/ProductList.tsx
  src/interfaces/product.ts
  src/pages/ProductDetailPage.tsx
  src/pages/ProductListPage.tsx
  src/states/products.ts
Labels: design

#49 [Fix] 제품 이미지 연결
  public/images/blog/thumbnail.jpg
  public/images/products/product1.png
  public/images/products/product2.png
  public/images/products/product3.png
  public/images/products/product4.png
  public/images/products/product5.png
  public/images/products/product6.png
  public/images/products/product7.png
  public/images/products/product8.png
  public/images/products/product9.png
  src/components/blog-list/Header.tsx
  src/components/product-detail/ProductDetail.tsx
  src/components/product-list/Categories.tsx
  src/components/product-list/ProductList.tsx
  src/data/blog.json
  src/data/product.js
  src/data/product.json
  src/interfaces/product.ts
Labels: fix

#51 [Fix] 네비게이션 바와 콘텐츠의 크기가 안 맞는 오류 수정
  src/components/navbar/Navbar.tsx
Labels: fix

#53 [Design] 구매정보 페이지
  src/Router.tsx
  src/assets/purchase/picture.svg
  src/components/auth/Agreement.tsx
  src/components/auth/Information.tsx
  src/components/auth/Login.tsx
  src/components/common/Box.tsx
  src/components/common/Input/Address.tsx
  src/components/common/Input/AuthInput.tsx
  src/components/common/Input/CheckBox.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/Radio.tsx
  src/components/common/Title/Header.tsx
  src/components/common/Title/SubTitle.tsx
  src/components/common/Title/Title.tsx
  src/components/purchase/PurchaseInformation.tsx
  src/pages/auth/SignupPage.tsx
  src/styles/theme.ts
Labels: design, fix

#64 [Feat] 하이카디 드롭다운 추가 및 드롭다운 디자인 수정
  src/components/common/NavActiveLink.tsx
  src/components/navbar/Navbar.tsx
  src/styles/theme.ts
Labels: feat

#65 [Design] 구매하기 페이지
  src/components/auth/Complete.tsx
  src/components/common/Title/Header.tsx
  src/components/purchase/OrderComplete.tsx
  src/components/purchase/Payment.tsx
  src/styles/theme.ts
Labels: design

#66 [Design] 뉴스 목록 페이지 완성
  public/images/icons/left-arrow.svg
  public/images/icons/right-arrow.svg
  public/images/placeholder/placeholder-image1.png
  src/Router.tsx
  src/components/navbar/Navbar.tsx
  src/components/news/ArticleList.tsx
  src/components/news/HeaderImage.tsx
  src/components/news/Heading.tsx
  src/data/news.json
  src/pages/NewsPage.tsx
Labels: design

#70 [Fix] 하이카디 드롭다운 스타일 지정 안되는 오류 수정
  src/components/navbar/Navbar.tsx
Labels: fix

#71 [Design] 제품 목록 페이지 디자인 수정
  src/components/product-list/Categories.tsx
  src/components/product-list/GrayWrapper.tsx
  src/components/product-list/Heading.tsx
  src/components/product-list/ProductList.tsx
  src/pages/ProductListPage.tsx
  src/states/product.ts
Labels: design

#72 [Design] 장바구니 페이지 완료
  public/images/check-button/checked.svg
  public/images/check-button/unchecked.svg
  public/images/icons/close.svg
  src/Router.tsx
  src/components/cart/CartContent.tsx
  src/components/cart/PurchaseAction.tsx
  src/components/common/GrayBackground.tsx
  src/components/product-detail/ProductDetail.tsx
  src/components/product-list/GrayWrapper.tsx
  src/components/product-list/Heading.tsx
  src/pages/CartPage.tsx
  src/pages/ProductListPage.tsx
Labels: design
